### ISSUE TITLE
Could not install npm dependencies under FreeBSD

### ISSUE THREAD

**Issue by narqo** [bem/bem-bl#280]
Trying to set up npm-dependencies for `bem-bl/0.3` under FreeBSD:

``` (sh)
$ uname -v
FreeBSD 8.2-STABLE
$ cd bem-bl && npm install 

> microtime@0.3.1 install /usr/home/varankinv/bem-bl/node_modules/microtime
> node-gyp rebuild

info it worked if it ends with ok 
spawn python [ '/home/varankinv/.node-gyp/0.6.17/tools/gyp_addon',
  'binding.gyp',
  '-I/usr/home/varankinv/bem-bl/node_modules/microtime/build/config.gypi',
  '-f',
  'make' ]
spawn make [ 'BUILDTYPE=Release', '-C', 'build' ]
"Makefile", line 17: Need an operator
"Makefile", line 19: Need an operator
"Makefile", line 21: Need an operator
"Makefile", line 115: Need an operator
"Makefile", line 117: Need an operator
"Makefile", line 119: Need an operator
"Makefile", line 128: Need an operator
"Makefile", line 129: Need an operator
"Makefile", line 218: Need an operator
"Makefile", line 231: Need an operator
"Makefile", line 239: Need an operator
Error expanding embedded variable.
ERR! Error: `make` failed with exit code: 2
    at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:212:23)
    at ChildProcess.emit (events.js:70:17)
    at maybeExit (child_process.js:362:16)
    at Process.onexit (child_process.js:398:5)
ERR! not ok
npm ERR! microtime@0.3.1 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the microtime@0.3.1 install script.
npm ERR! This is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.

npm ERR! System FreeBSD 8.2-STABLE
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /usr/home/varankinv/bem-bl
npm ERR! node -v v0.6.17
npm ERR! npm -v 1.1.25
npm ERR! code ELIFECYCLE
npm ERR! message microtime@0.3.1 install: `node-gyp rebuild`
npm ERR! message `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/home/varankinv/bem-bl/npm-debug.log
npm ERR! not ok code undefined
npm ERR! not ok code 1
```

**Comment by arikon** [comment]
If think we could explicitly use `gmake` here on FreeBSD.

**Comment by tadatuta** [comment]
:+1:  vote for this issue

**Comment by arikon** [comment]
@narqo Could you check this with `node 0.8.x`?

**Comment by narqo** [comment]
Tested with `node 0.8.14` – works fine with `microtime@0.3.2`.

I think we could push our BSD-jails to move on `0.8.x` (because of #293)? 

/cc @veged @mishanga

**Comment by deeonis** [comment]
Закрываю за давностью лет
