### ISSUE TITLE
Don't rename global variables

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-bl#307]
Now it's impossible to check presence of BEM variable in js block. But it's possible in predicate.

It'd be great to have both possibilities.

E.g.

``` javascript
attrs: {
        var lang = (BEM && BEM.I18N) ? BEM.I18N.lang() : 'en';
     }
}
```

will result in error if BEM is not present:

```
12:50:43.592 - warn: *** HTTP error: 500, ReferenceError: BEM is not defined
   at Object.$192 (/home/motus/_projects/airomo/airomo-bem/pages-desktop/fb-app/fb-app.bemhtml.js:523:36)
   at Object.$186 (/home/motus/_projects/airomo/airomo-bem/pages-desktop/fb-app/fb-app.bemhtml.js:406:29)
   at Object.apply (/home/motus/_projects/airomo/airomo-bem/pages-desktop/fb-app/fb-app.bemhtml.js:347:25)

/* and so on */

at Array.$475 (/home/motus/_projects/airomo/airomo-bem/pages-desktop/fb-app/fb-app.bemhtml.js:1337:16)
   at Array.$473 (/home/motus/_projects/airomo/airomo-bem/pages-desktop/fb-app/fb-app.bemhtml.js:1117:25)
   at Array.$467 (/home/motus/_projects/airomo/airomo-bem/pages-desktop/fb-app/fb-app.bemhtml.js:1084:25)
   at Array.$192 (/home/motus/_projects/airomo/airomo-bem/pages-desktop/fb-app/fb-app.bemhtml.js:846:25)
   at Array.$186 (/home/motus/_projects/airomo/airomo-bem/pages-desktop/fb-app/fb-app.bemhtml.js:409:25)
   at Array.apply (/home/motus/_projects/airomo/airomo-bem/pages-desktop/fb-app/fb-app.bemhtml.js:347:25)
   at Array.<anonymous> (/home/motus/_projects/airomo/airomo-bem/pages-desktop/fb-app/fb-app.bemhtml.js:1576:23)
   at exports.techMixin.getHtml (/home/motus/_projects/airomo/airomo-bem/bem-bl/blocks-common/i-bem/bem/techs/html.js:33:32)
   at exports.async (/home/motus/_projects/airomo/airomo-bem/node_modules/bem/node_modules/q/q.js:986:30)
   at _fulfilled (/home/motus/_projects/airomo/airomo-bem/node_modules/bem/node_modules/q/q.js:927:32)
   at resolvedValue.promiseSend.done (/home/motus/_projects/airomo/airomo-bem/node_modules/bem/node_modules/q/q.js:953:30)
   at makePromise.promise.promiseSend (/home/motus/_projects/airomo/airomo-bem/node_modules/bem/node_modules/q/q.js:587:13)
   at promise.promiseSend (/home/motus/_projects/airomo/airomo-bem/node_modules/bem/node_modules/q/q.js:465:35)
   at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

At the same time

``` javascript
BEM, BEM.I18N, (BEM.I18N.lang() != 'en'), attrs: {
        var lang = BEM.I18N.lang();
}
```

will work as expected.

**Comment by narqo** [comment]
_Not in case of issue_

It will be more useful to add "default" implementation for `BEM.I18N.lang()` method, just like we did with `BEM.I18N()` (see https://github.com/bem/bem-bl/blob/master/blocks-common/i-bem/__i18n/i-bem__i18n.bemhtml for details)

**Comment by arikon** [comment]
cc @indutny

**Comment by deeonis** [comment]
Закрываю за давностью лет
